const { PrismaClient } = require('@prisma/client');
const jwt = require('jsonwebtoken');
const { compare, hash } = require('../src/utils/password');
const { signAccess } = require('../src/utils/jwt');

const prisma = new PrismaClient();

const optional = (value) => {
  if (value === undefined || value === null) return undefined;
  const trimmed = String(value).trim();
  return trimmed.length ? trimmed : undefined;
};

const required = (name) => {
  const value = optional(process.env[name]);
  if (!value) throw new Error(`${name} is required`);
  return value;
};

const parseFloatEnv = (name) => {
  const value = optional(process.env[name]);
  if (!value) return undefined;
  const parsed = Number.parseFloat(value);
  if (!Number.isFinite(parsed)) throw new Error(`${name} must be a number`);
  return parsed;
};

const parseIntEnv = (name, fallback) => {
  const value = optional(process.env[name]);
  if (!value) return fallback;
  const parsed = Number.parseInt(value, 10);
  if (!Number.isInteger(parsed) || parsed <= 0) throw new Error(`${name} must be a positive integer`);
  return parsed;
};

function configFromEnv() {
  const houseName = optional(process.env.PILOT_HOUSE_NAME);
  const houseAddress = optional(process.env.PILOT_HOUSE_ADDRESS);
  const houseLatitude = parseFloatEnv('PILOT_HOUSE_LATITUDE');
  const houseLongitude = parseFloatEnv('PILOT_HOUSE_LONGITUDE');

  if ([houseName, houseAddress, houseLatitude, houseLongitude].some((v) => v !== undefined)) {
    if (!houseName || !houseAddress || houseLatitude === undefined || houseLongitude === undefined) {
      throw new Error('PILOT_HOUSE_NAME, PILOT_HOUSE_ADDRESS, PILOT_HOUSE_LATITUDE, and PILOT_HOUSE_LONGITUDE are all required when creating a pilot house');
    }
    if (houseLatitude < -90 || houseLatitude > 90) throw new Error('PILOT_HOUSE_LATITUDE must be between -90 and 90');
    if (houseLongitude < -180 || houseLongitude > 180) throw new Error('PILOT_HOUSE_LONGITUDE must be between -180 and 180');
  }

  const managerPassword = required('PILOT_MANAGER_PASSWORD');
  if (managerPassword.length < 8) throw new Error('PILOT_MANAGER_PASSWORD must be at least 8 characters');

  return {
    dryRun: process.argv.includes('--dry-run') || process.env.PILOT_SETUP_DRY_RUN === 'true',
    agencyId: optional(process.env.PILOT_AGENCY_ID),
    agencyName: required('PILOT_AGENCY_NAME'),
    managerName: required('PILOT_MANAGER_NAME'),
    managerEmail: required('PILOT_MANAGER_EMAIL').toLowerCase(),
    managerPassword,
    managerPhone: optional(process.env.PILOT_MANAGER_PHONE),
    house: houseName
      ? {
          name: houseName,
          address: houseAddress,
          latitude: houseLatitude,
          longitude: houseLongitude,
          geofenceRadius: parseIntEnv('PILOT_HOUSE_GEOFENCE_RADIUS', 50),
        }
      : null,
  };
}

async function findAgency(config) {
  if (config.agencyId) {
    return prisma.agency.findUnique({ where: { id: config.agencyId } });
  }
  return prisma.agency.findFirst({ where: { name: config.agencyName } });
}

async function setupPilotAgency(config) {
  if (config.dryRun) {
    return {
      dryRun: true,
      agency: {
        id: config.agencyId || '(generated by Prisma)',
        name: config.agencyName,
        action: 'would create or reuse',
      },
      manager: {
        email: config.managerEmail,
        name: config.managerName,
        role: 'MANAGER',
        action: 'would create or update if already in this agency',
      },
      house: config.house ? { name: config.house.name, action: 'would create or update inside this agency' } : null,
    };
  }

  const existingAgency = await findAgency(config);
  const existingManager = await prisma.user.findUnique({ where: { email: config.managerEmail } });

  if (existingManager && existingAgency && existingManager.agencyId !== existingAgency.id) {
    throw new Error(`Manager email already belongs to another agency: ${existingManager.agencyId}`);
  }
  if (existingManager && !existingAgency) {
    throw new Error(`Manager email already exists before pilot agency creation: ${existingManager.agencyId}`);
  }
  if (existingAgency && existingManager && existingManager.role !== 'MANAGER' && existingManager.role !== 'HR') {
    throw new Error(`Existing manager email has unsupported role: ${existingManager.role}`);
  }

  const passwordHash = await hash(config.managerPassword);

  const agency = existingAgency
    ? await prisma.agency.update({
        where: { id: existingAgency.id },
        data: { name: config.agencyName },
      })
    : await prisma.agency.create({
        data: {
          ...(config.agencyId ? { id: config.agencyId } : {}),
          name: config.agencyName,
        },
      });

  const manager = existingManager
    ? await prisma.user.update({
        where: { id: existingManager.id },
        data: {
          agencyId: agency.id,
          name: config.managerName,
          passwordHash,
          role: existingManager.role === 'HR' ? 'HR' : 'MANAGER',
          status: 'ACTIVE',
          phone: config.managerPhone || null,
          deactivatedAt: null,
          deactivatedById: null,
          deactivationReason: null,
        },
      })
    : await prisma.user.create({
        data: {
          agencyId: agency.id,
          name: config.managerName,
          email: config.managerEmail,
          passwordHash,
          role: 'MANAGER',
          status: 'ACTIVE',
          phone: config.managerPhone || null,
        },
      });

  let house = null;
  if (config.house) {
    const existingHouse = await prisma.house.findFirst({
      where: { agencyId: agency.id, name: config.house.name },
    });
    house = existingHouse
      ? await prisma.house.update({
          where: { id: existingHouse.id },
          data: { ...config.house, managerId: manager.id },
        })
      : await prisma.house.create({
          data: { agencyId: agency.id, ...config.house, managerId: manager.id },
        });
  }

  const passwordMatches = await compare(config.managerPassword, manager.passwordHash);
  if (!passwordMatches) {
    throw new Error('Pilot manager password verification failed');
  }
  const tokenPayload = {
    id: manager.id,
    agencyId: manager.agencyId,
    role: manager.role,
    status: manager.status,
    name: manager.name,
    email: manager.email,
  };
  const decoded = jwt.decode(signAccess(tokenPayload));
  if (!decoded || decoded.agencyId !== agency.id) {
    throw new Error('Pilot manager token verification failed');
  }

  return {
    dryRun: false,
    agency: { id: agency.id, name: agency.name },
    manager: { id: manager.id, email: manager.email, role: manager.role, agencyId: manager.agencyId },
    house: house ? { id: house.id, name: house.name, agencyId: house.agencyId } : null,
    loginTokenAgencyIdVerified: true,
  };
}

async function main() {
  const config = configFromEnv();
  const result = await setupPilotAgency(config);
  console.log(JSON.stringify(result, null, 2));
}

main()
  .catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
